### PR TITLE
set basic keybindings

### LINKED ISSUE #2: Set mouse Keybindings for the views
Mouse click handlers
- [x] cluster-info
- [x] namespace
- [x] resource
- [x] infoview

Exit handler
- [x] Ctrl+C

Tab handler
- [x] resource
- [x] info

### PR DESCRIPTION
**Pull request by yolossn**
Fix #2

### CODE REVIEW

**Review by GnaneshKunal — APPROVED** [review]
Everything works fine but segfaults while handling CTRL-C

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0x10e6f15]

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0001020b0, 0x0, 0xc000079e38, 0xc000000208, 0xc000079e20, 0xc0000002b8)
	/Users/monster/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200201013258-57fdcf23edc5/gui.go:816 +0xb5
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0001020b0, 0xc000079e38, 0x2, 0x0)
	/Users/monster/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200201013258-57fdcf23edc5/gui.go:762 +0x28d
github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/Users/monster/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200201013258-57fdcf23edc5/gui.go:485
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0001020b0, 0xc0001020b0, 0x0)
	/Users/monster/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200201013258-57fdcf23edc5/gui.go:445 +0x20a
github.com/yolossn/lazykubernetes/pkg/gui.(*Gui).Run(0xc00000e038, 0x0, 0x0)
	/Users/monster/self/lazykubernetes/pkg/gui/gui.go:45 +0x1b0
github.com/yolossn/lazykubernetes/pkg/app.(*App).Run(...)
	/Users/monster/self/lazykubernetes/pkg/app/app.go:12
main.main()
	/Users/monster/self/lazykubernetes/main.go:11 +0x52
exit status 2
```

**Comment by GnaneshKunal** [comment]
@yolossn 

We can still merge it by creating another issue about the segfault.

**Comment by yolossn** [comment]
> @yolossn
> 
> We can still merge it by creating another issue about the segfault.

This happens randomly,  lets track it as separate issue.

**Comment by GnaneshKunal** [comment]
> > @yolossn
> > We can still merge it by creating another issue about the segfault.
> 
> This happens randomly, lets track it as separate issue.

Okay.

**Pull request merged**
